services:
  app:
    image: ${ECR_IMAGE}:${TAG:-latest}
    env_file: .env
    pull_policy: always
    restart: unless-stopped

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./infra/Caddyfile:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on: [app]
    restart: unless-stopped
